### ISSUE TITLE
The sytax highlighting is off

### ISSUE THREAD

**Issue by Eugleo** [pouyakary/vscode-racket#3]
Hey! I'm happy there is an extension to support Racket in VS Code, but I have to say the syntax highlighting is sometimes questionable. The list of (some of the) errors follows:

- everything in a sexp is a `constant.numeric`
- multiline strings don't work
- no languge keywords
- quoting doesn't have any impact on the syntax highlighting
- function parameters are not correctly marked as such

I'm working with Racket quite a lot lately and I'd be willing to work on making the syntax highlighting better. Are you open to PRs in this area? Also, I'm not sure whether the changes wouldn't interfere with the extension code ~zou~ you provide to have better IntelliSense. Could you explain to me how does it work (and what are all the orchestra files), so I will be able to work around it?

**Comment by pouyakary** [comment]
Hi! I'm not a pro Racket developer and I rarely code in Racket so there are many areas which I'm probably not covered. What I did in order to test the highlighting was to open the main Racket compiler's codes and look for errors.

Currently I'm very short in time and Racket for VS Code is not in my priorities. So yeah any PR would be such a big help. [Orchestra Lang](https://github.com/pmkary/Orchestra) is a project I've been working on for sometime that is a better language than RegEx and compiles to plain RegExp. Developing syntax highlighters require a lots of non-readable RegExes and so I prefer to write those RegExes using Orchestra but there is no requirement to only do them with Orchestra.

I don't know about _zou_ but I tried to incorporate Dr. Racket's autocomplete facilities into this extension. I found out that it's more complicated than it seems as it's a core part of the actual IDE and is hardly accessible outside of it. So what I did instead was going more like other Racket editor supports: A code scanner that finds identifiers + a list of known language-core identifiers and library objects. It's not context-aware or anything but just a little better code completion.

Given all that, If you ever had any PR, I would be very happy to merge them.

**Comment by Eugleo** [comment]
_The "zou" was actually a typo of "you" (got it fixed in the original post now)._

Great! Don't get me wrong, Racket for VS Code has still the best syntax highlighting in comparison with the other Racket extensions on the marketplace. It just could be a little bit better. I'll work on it and make a PR ASAP. 

Off-topic, Orchestra indeed seems cool! I had to resist the urge to learn it and port the existing WIP files to it; I think I should get some actual work done now, but will deffinitely be checking out Orchestra later.
